/**
 * Shared type definitions for the specification wizard
 * Centralizes form data interfaces to prevent duplication
 */

import { Specification } from '@/types'
import { UseFormReturn } from 'react-hook-form'
import { Product } from '@/lib/types/product'
import { SpecificationEnumData } from '@/types/enum'

// Form data type based on canonical Specification interface
// Omit only id (auto-generated by database)
export type WizardFormData = Omit<Specification, 'id'>

export interface UseSpecificationWizardProps {
  onSubmit: (data: Specification) => void | Promise<void>
  initialData?: Record<string, unknown>
  userId: string
}

export interface UseSpecificationWizardReturn {
  methods: UseFormReturn<WizardFormData>
  activeStep: number
  completedSteps: Set<number>
  isSubmitting: boolean
  selectedProduct: Product | null
  enumData: SpecificationEnumData | undefined
  enumsLoading: boolean
  filteredProducts: Product[]
  handleNext: () => void
  handlePrevious: () => void
  handleStepClick: (stepIndex: number) => void
  handleFormSubmit: (data: WizardFormData) => Promise<void>
  canNavigateToStep: (stepIndex: number) => boolean
}

export interface UseSubmissionProps {
  onSubmit: (data: Specification) => void | Promise<void>
  methods: UseFormReturn<WizardFormData>
  userId: string
}

export interface UseSpecificationSubmissionReturn {
  isSubmitting: boolean
  handleFormSubmit: (formData: WizardFormData) => Promise<void>
}
